// This file is generated by packages/protocol/scripts/generate-embedded-feature-policies.mjs
// Do not edit by hand.

export const DEFAULT_EMBEDDED_FEATURE_POLICY_ENV = "preview" as const;

const EMBEDDED_FEATURE_BUILD_POLICY_RAW_INNER = {
  preview: {
    allowRaw: "",
    denyRaw: "",
  },
  production: {
    allowRaw: "",
    denyRaw: "",
  },
} as const;

export const EMBEDDED_FEATURE_BUILD_POLICY_RAW = Object.freeze({
  preview: Object.freeze({ ...EMBEDDED_FEATURE_BUILD_POLICY_RAW_INNER.preview }),
  production: Object.freeze({ ...EMBEDDED_FEATURE_BUILD_POLICY_RAW_INNER.production }),
}) as typeof EMBEDDED_FEATURE_BUILD_POLICY_RAW_INNER;
